### ISSUE TITLE
MCP Params not parsed correctly?

### ISSUE THREAD

**Issue by thecatcore** [unimined/UniminedMappingLibrary#1]
When parsing MCP mappings with both `joined.exc` and `params.csv`.

Generated mappings end up having 2 entries per parameter where: 
- one is based on param index and is named in both searge and mcp.
- the other is based on param lvOrd and is named in mcp only.

In Unimined, when remapping params, only lvOrd is checked for param validity so currently it's impossible to remap a mc jar to searge only with the right parameter names.

Example with mcp for MC1.3.2:
```
c	aa	net/minecraft/src/CommandTime	net/minecraft/src/CommandTime
	m	a;(Lr;)Ljava/lang/String;	func_71518_a;(Lnet/minecraft/src/ICommandSender;)Ljava/lang/String;	getCommandUsage;(Lnet/minecraft/src/ICommandSender;)Ljava/lang/String;
		p	0	_	_	p_71518_1_	par1ICommandSender
		p	_	1	_	_	par1ICommandSender
```
Constructors seem to be affected differently:
```
m	<init>;(Ljava/util/Random;II)V	<init>;(Ljava/util/Random;II)V	<init>;(Ljava/util/Random;II)V
		p	0	_	_	p_i3835_1_	par1Random
		p	1	_	_	p_i3835_2_	par2
		p	2	_	_	p_i3835_3_	par3
```

**Comment by wagyourtail** [comment]
I believe this is fixed as of latest snapshots
